### ISSUE TITLE
部署多节点本地自动测试网

### ISSUE THREAD

**Issue by Assassinwang64** [bianjieai/irita#122]
在多节点本地自动测试网时构建 linux 二进制出现如下错误：
root@iZhp3ayq4cervqam4wcj2yZ:~/wenchang/irita-master# make build-linux
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Unknown flag: --swagger_opt
Makefile:135: recipe for target 'proto-swagger-gen' failed
make: *** [proto-swagger-gen] Error 1

**Comment by chengwenxi** [comment]
@Assassinwang64 `make  proto-tools` to install the proto-related tools.

**Comment by chengwenxi** [comment]
It seems that `update-swagger-docs` of `make build-linux` is redundant, we can remove it. @zhangyelong

**Comment by Assassinwang64** [comment]
we try make proto-tools, and still have same problems.
root@iZhp3ayq4cervqam4wcj2yZ:~/wenchang/irita-master# make proto-tools
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Installing buf...
touch buf-stamp
protoc already installed; skipping...
Installing protoc-gen-gocosmos...
protoc-gen-grpc-gateway already installed; skipping...
protoc-gen-swagger already installed; skipping...
root@iZhp3ayq4cervqam4wcj2yZ:~/wenchang/irita-master# make build-linux
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Unknown flag: --swagger_opt
Makefile:135: recipe for target 'proto-swagger-gen' failed
make: *** [proto-swagger-gen] Error 1

**Comment by chengwenxi** [comment]
just remove update-swagger-docs in https://github.com/bianjieai/irita/blob/master/Makefile#L84
