### ISSUE TITLE
启动本地单节点测试网报错

### ISSUE THREAD

**Issue by katoyi120** [bianjieai/irita#208]
我在按照[官方部署文档](https://irita.bianjie.ai/docs/installation/deployment.html) 部署本地单节点,在最后一步启动节点的时候报了错,请问一下这个错误的原因是什么?以及如何更正这个错误.
![image](https://user-images.githubusercontent.com/45357125/173032039-7816262c-882e-4183-ac5d-64ba0d8e0b71.png)

**Comment by shenyue001** [comment]
你好，这个需要在启动前修改一下genesis文件。 在 token.tokens 下添加
```
{
          "symbol": "point",
          "name": "Irita base native token",
          "scale": 6,
          "min_unit": "upoint",
          "initial_supply": "1000000000",
          "max_supply": "18446744073709551615",
          "mintable": true,
          "owner": ""
 }
```


另外，报这个错误的话，需要清除数据，重新再启动了（完全重新操作一次）。
